import Head from 'next/head'
import React from 'react'
import classes from '../styles/styles.module.css'
const Layout = (props) => {
    return (
        <React.Fragment>
            <Head>
                <title>Job Posts</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <header className = {classes.header}>
                <div className = {classes.navbar}>
                    <div className = {classes.title}>
                        <h2>Job Posting</h2>
                    </div>
                </div>
            </header>
            <div className = {classes.toolbar}></div>
            <div className = {classes.body}>
                {props.children}
            </div>
        </React.Fragment>
    )
}

export default Layout
